# SPDX-FileCopyrightText: 2026 Vitor Mattos
# SPDX-License-Identifier: AGPL-3.0-or-later
version = 1

[[annotations]]
path = [
    "composer.json"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Vitor Mattos"
SPDX-License-Identifier = "AGPL-3.0-or-later"
