# SPDX-FileCopyrightText: 2026 Vitor Mattos
# SPDX-License-Identifier: AGPL-3.0-or-later
version = 1

[[annotations]]
path = [
    ".prettierrc.json",
    ".stylelintrc.json",
    "composer.json",
    "package.json",
    "source/robots.txt.blade.php"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Vitor Mattos"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = [
    "presentations/slides.com/**",
    "presentations/slideshare/**"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Vitor Mattos"
SPDX-License-Identifier = "CC-BY-SA-4.0"
